# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
#
pod 'TesseractOCRiOS', '3.4.0'
pod 'GPUImage', '0.1.6'
pod 'Venmo-iOS-SDK', '~>1.3'

target 'Splitr' do

end


